import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "pedroTech Tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="mt-4">
          <Link
            className="bg-green-500 p-2 m-2 rounded-md hover:bg-green-600 active:bg-green-700"
            href="./"
          >
            Home
          </Link>
          <Link
            className="bg-green-500 p-2 m-2 rounded-md hover:bg-green-600 active:bg-green-700"
            href={"./about"}
          >
            About
          </Link>
          <Link
            className="bg-green-500 p-2 m-2 rounded-md hover:bg-green-600 active:bg-green-700"
            href="./contact"
          >
            Contact
          </Link>
          <Link
            className="bg-green-500 p-2 m-2 rounded-md hover:bg-green-600 active:bg-green-700"
            href="./users"
          >
            Users
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
