"use client";
import { Metadata } from "next";
import { useState } from "react";

// every component is a server component. But to make it client component it should be written like this

const metadata: Metadata = {
  title: "About us | Name of the website",
  description: "Generated by create next app",
  keywords: "post, company...",
  twitter: {
    card: "summary_large_image",
    title: "About us | Twitter",
  },
};

async function makePostRequest() {
  const res = await fetch("./api/hello", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ name: "Naim" }),
  });

  const data = await res.json();
  return { data };
}

const About = async () => {
  const [message, setMessage] = useState("");

  console.log(`Is this a server or a client component?`);
  const onClick = async () => {
    const { data } = await makePostRequest();
    setMessage(data.message);
  };
  return (
    <>
      <h1>
        About Page, {message}{" "}
        <button className="cursor-pointer" onClick={onClick}>
          Click Me!
        </button>
      </h1>
    </>
  );
};

export default About;
